name: Loan Approval CI/CD Pipeline

on:
  # Trigger saat ada push ke branch main
  push:
    branches:
      - main
  # Trigger saat ada pull request ke branch main
  pull_request:
    branches:
      - main
  # Trigger manual lewat UI GitHub
  workflow_dispatch:

env:
  MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
  
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install mlflow dagshub pandas scikit-learn xgboost matplotlib docker

    - name: Run Training Script
      working-directory: MLProject
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        python modelling.py

    - name: Get Latest MLflow Run ID
      working-directory: MLProject
      run: |
        RUN_ID_FILE="artifacts/best_run_id.txt"

        if [ -f "$RUN_ID_FILE" ]; then
          RUN_ID=$(cat "$RUN_ID_FILE")
          echo "Found Run ID: $RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        else
          echo "Error: best_run_id.txt not found!"
          echo "Pastikan script python sudah menulis file ini."
          exit 1
        fi

    - name: Upload to GitHub Artifacts
      if: env.RUN_ID != ''
      uses: actions/upload-artifact@v4
      with:
        name: loan-approval-artifacts-${{ env.RUN_ID }}
        path: |
          MLProject/artifacts
          MLProject/*.json
          MLProject/*.png
        retention-days: 90

    - name: Login to Docker Hub
      if: env.RUN_ID != ''
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      if: env.RUN_ID != ''
      run: |
        IMAGE_NAME="${{ env.DOCKERHUB_USERNAME }}/loan-approval-model"
        
        echo "Building Docker image: $IMAGE_NAME:$RUN_ID"

        # Perintah build MLflow
        mlflow models build-docker \
          --model-uri "runs:/$RUN_ID/model" \
          --name "$IMAGE_NAME:$RUN_ID"

        # Tag juga sebagai 'latest'
        docker tag "$IMAGE_NAME:$RUN_ID" "$IMAGE_NAME:latest"

    - name: Push Docker Image
      if: env.RUN_ID != ''
      run: |
        IMAGE_NAME="${{ env.DOCKERHUB_USERNAME }}/loan-approval-model"
        
        docker push "$IMAGE_NAME:$RUN_ID"
        docker push "$IMAGE_NAME:latest"
